export default [
  { hed: 'Opening' },
  {
    hed: 'Amritsar',
    dek: "We had set out from Bangalore and reached New Delhi via flight. Because of poor weather conditions, we had to avoid the bus route from Delhi. So, after a day's pit stop, that we used to catch up on our secondary research and refine our itinerary, we took a morning flight to Amritsar.",
    img: 'sunrise.jpg',
    alt: 'A photograph of a sunrise captured from an aeroplane window.',
    caption:
      'The view of sunrise from the flight was breathtakingly beautiful!',
  },
  {
    hed: 'Palampur',
    dek: 'After a hearty breakfast comprising of Kulcha and Lassi, we rented a car and set out on a five-hour journey to Palampur via 235km of NH54 and NH154. We had luckily received permission to put up at the CSIR-IHBT guest house for the course of our research, which gave us the opportunity to meet some amazing people and learn about the ground-breaking research being conducted there using the Himalayan bio-resources.',
    img: 'ihbt.jpg',
    alt: '',
    caption: 'Amidst the plantations inside the IHBT campus',
  },
  {
    hed: 'Andretta',
    dek: 'Being a prime focus of our tour, we made sure that we captured the place in as much detail as possible. Our first stop was the residence cum gallery of Shobha Singh, a well-known contemporary painter from Indian Punjab, that has now been turned into an art museum, showcasing his life and works. We also visited a dance and music school, located nearby, where we got to hear about the local music and dance styles. We might also have picked up some Kangri dance moves from the instructor!',
    img: 'shobha.jpg',
    alt: '',
    caption: 'View of the residence from the road',
  },
  {
    hed: '',
    dek: "We then visited the residence and theatre of Norah Richards, an Irish-born actress who had settled in Andretta in 1924 and used to teach drama and playwriting to students. The place is now maintained by the Punjabi University at Patiala. It's no wonder the place of Andretta has always been deeply rooted in artistic and cultural treasures.",
    img: 'norah.jpg',
    alt: '',
    caption: 'A rose shrub by the lane to the entrance.',
  },
  {
    hed: '',
    dek: 'The visit to the pottery studio was quite an experience as we were heartily welcomed by the artists, the students and two canine residents of the place.',
    img: 'dog.jpg',
    alt: '',
    caption: 'Our canine friend drying off in the sun',
  },
  {
    hed: '',
    dek: 'We were shown around the place by Shubham, the young and vibrant potter and manager of the studio. We took a tour of the studio, the museum and the store. We also interviewed Mansimran Singh, which helped us strategize the rest of the research. In the days to come, we documented the birth of a vase from throwing to glazing, interviewed other potters and the students who had come to the place for training.',
    img: 'vase.jpg',
    alt: '',
    caption: 'The finished vase basking in the lap of nature',
  },
  {
    hed: '',
    dek: "Our next stop was The Mirage. Even though we had reached unannounced, the hosts were kind enough to invite us to lunch. The beautiful place, equipped with a meditation centre, provided a much needed escape to people from the bustle of the city life from across the country and the world. We had the opportunity to interview Navjot, one of the hosts, who was a theatre artist and poet herself. She gave us an idea of the cultural richness of the region and how it was dwindling. She also gave us a tour of the artists' residency she was working on.",
    img: 'mirage.jpg',
    alt: '',
    caption: 'The much cherished lunch at The Mirage',
  },
  {
    hed: 'Wah Tea Estate',
    dek: "It was afternoon by the time we reached the estate on our way back to IHBT campus. The place derives its name from 'Wah' in Pakistan — the first owner was the Nawab of Wah. In 1953, the estate was taken over by the 'Chaiwala Family'. Wah has passed hands within the family and is now looked after by Deepak and Surya, who gave us an elaborate tour of the estate and the tea processing units. Oh, we did some tea tasting too!",
    img: 'wah.jpg',
    alt: '',
    caption: 'The tea plants ready for fine-plucking',
  },
  {
    hed: 'Ashapuri',
    dek: 'Believed to have been built by the Pandavas, Ashapuri Mata Temple is an important religious destination located on the top of the hill. The drive to the place and watching the sunset from the hill was an experience in itself.',
    img: 'ashapuri.jpg',
    alt: '',
    caption: 'Viewing the sunset from the top',
  },
  {
    hed: 'Baijnath',
    dek: 'We had kept an entire day to go around the city of Palampur to visit some popular spots and observe the people and life in the Kangra valley. On our way, we did encounter a herd of the Gaddi tribe.',
    img: 'gaddi.jpg',
    alt: '',
    caption: 'The herd follows its own route through the hills',
  },
  {
    hed: '',
    dek: 'We headed for the Tashi Jong village, the Tibetan settlement, that houses a monastery that is one of the schools of Drugpa Kagyu tradition of Buddhism.',
    img: 'tashi.jpg',
    alt: '',
    caption: 'Prayer wheels at the entrance of the monastery',
  },
  {
    hed: '',
    dek: 'We were quite famished by the time we left Tashi Jong. Upon the suggestion of our cabbie, combined with our excitement to dine at a palace hotel, we headed towards the Taragarh Palace. The palace stands majestically at a height of 1,000 meters, amidst 15 acres of lush forests and tea gardens in the Kangra Valley. The palace was built as a summer resort and was acquired by the Royal Family of Jammu & Kashmir in 1951. Developed as a Heritage Hotel in 1971, Taragarh Palace hotel offers splendid views of the snow-clad ranges of the Dhauladhar Mountains.',
    img: 'taragarh.jpg',
    alt: '',
    caption: 'View of the hotel building from the garden',
  },
  {
    hed: '',
    dek: 'After lunch, we decided to head towards the famous 13th century temple of Baijnath, dedicated to Lord Shiva as Vaidyanath — the Lord of the Physicians. Even though the place was crowded with devotees, we got a chance to get a peek inside the temple. A flight of steps from the temple leads down to the banks of the Kheerganga that flows through Baijnath.',
    img: 'kheer.jpg',
    alt: '',
    caption: 'Streams of Kheerganga at Baijnath',
  },
  {
    hed: 'Bir-Billing',
    dek: 'On the final day of our Palampur tour, we decided to conclude with some experience of adventure. Hence, we headed towards Bir-Billing, the best spot for paragliding aero-sport in India and the 2nd best in the world! For a flight spanning 15-25 minutes, we engaged in a tandem paragliding experience from Billing to Bir. The take-off point is located at Billing, 16 km uphill from Bir, at a height of 2438.4 meters above sea-level. The landing site in Bir is a plain field at about 1310.6 meters above sea-level. It indeed is an amazing experience to fly!',
    img: 'bir.jpg',
    alt: '',
    caption: "Jasleen enjoying her bird's-eye view of the valley",
  },
  { hed: 'Closing' },
];
