import * as p from '@clack/prompts';

import { basename, dirname, join, resolve } from 'path';
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from 'fs';

import { csvParse } from 'd3-dsv';
import { fileURLToPath } from 'url';
import sharp from 'sharp';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const ROOT = resolve(__dirname, '..');

/**
 * @param {string} dir
 * @param {string} ext
 * @returns {string[]}
 */
function findFiles(dir, ext) {
  const full = resolve(ROOT, dir);
  if (!existsSync(full)) return [];
  return readdirSync(full)
    .filter((f) => f.endsWith(ext))
    .map((f) => join(dir, f));
}

/**
 * @param {string} dir
 * @returns {string[]}
 */
function findComponentDirs(dir) {
  const full = resolve(ROOT, dir);
  if (!existsSync(full)) return [];
  /** @type {string[]} */
  const dirs = [];
  for (const entry of readdirSync(full)) {
    const p = join(full, entry);
    if (statSync(p).isDirectory()) {
      const index = join(p, 'index.svelte');
      if (existsSync(index)) {
        dirs.push(join(dir, entry));
      }
    }
  }
  return dirs;
}

/**
 * @param {Array<Record<string, string>>} rows
 * @param {string} col
 * @param {boolean} split
 * @returns {Array<{name: string, value: number, indices: number[]}>}
 */
function count(rows, col, split) {
  /** @type {Map<string, {name: string, value: number, indices: number[]}>} */
  const map = new Map();
  for (let i = 0; i < rows.length; i++) {
    const row = rows[i];
    const val = row[col];
    if (!val) continue;
    if (split) {
      for (const part of val.split(',')) {
        const tag = part.trim();
        if (tag) {
          if (!map.has(tag)) map.set(tag, { name: tag, value: 0, indices: [] });
          map.get(tag).value += 1;
          map.get(tag).indices.push(i);
        }
      }
    } else {
      if (!map.has(val)) map.set(val, { name: val, value: 0, indices: [] });
      map.get(val).value += 1;
      map.get(val).indices.push(i);
    }
  }
  return Array.from(map.values()).sort((a, b) => b.value - a.value);
}

/**
 * @param {Array<Record<string, string>>} rows
 * @param {string[]} columns
 * @param {Set<string>} multiCols
 * @returns {{ code: string, data: Record<string, Array<{name: string, value: number, indices: number[]}>> }}
 */
function precomputeAll(rows, columns, multiCols) {
  /** @type {Record<string, Array<{name: string, value: number, indices: number[]}>>} */
  const map = {};
  for (const col of columns) {
    map[col] = count(rows, col, multiCols.has(col));
  }

  const colsJson = JSON.stringify(map);
  const itemsJson = JSON.stringify(rows);

  const code = `// Auto-generated by scripts/count-gallery.js --precompute
const _items = ${itemsJson};
const _cols = ${colsJson};

export function getCounts(col) {
  return (_cols[col] || []).map(g => ({ name: g.name, value: g.value }));
}

export function getGroup(col, name) {
  const group = (_cols[col] || []).find(g => g.name === name);
  if (!group) return null;
  return { name: group.name, value: group.value, items: group.indices.map(i => _items[i]) };
}

export function getItems(col, name) {
  const group = getGroup(col, name);
  return group ? group.items : [];
}

export function getAllRows() {
  return _items;
}
`;

  return { code, data: map };
}

function fmt(s) {
  return s.replace(/_/g, ' ').replace(/\b\w/g, (l) => l.toUpperCase());
}

async function main() {
  const isPrecompute = process.argv.includes('--precompute');
  const args = process.argv.slice(2).filter((a) => !a.startsWith('--'));

  // ── pick CSV ────────────────────────────────────────────
  const csvFiles = findFiles('src/contents/data', '.csv');
  if (!csvFiles.length) {
    p.cancel('No CSV files found in src/contents/data/');
    process.exit(1);
  }

  let csvPath;
  if (args[0]) {
    const match = csvFiles.find((f) => f.endsWith(args[0]));
    csvPath = match || csvFiles[0];
  } else {
    csvPath = await p.select({
      message: 'Which gallery CSV file to use?',
      options: csvFiles.map((f) => ({
        value: f,
        label: f.replace('src/contents/data/', ''),
      })),
    });
    if (p.isCancel(csvPath)) {
      p.cancel();
      process.exit(0);
    }
  }

  const raw = readFileSync(resolve(ROOT, csvPath), 'utf-8');
  const rows = csvParse(raw);

  // Measure all images to embed w/h for placeholder blocks
  for (const row of rows) {
    const filePath = resolve(ROOT, 'static', 'media', row.url);
    try {
      const meta = await sharp(filePath).metadata();
      row.w = meta.width;
      row.h = meta.height;
      row.aspect = meta.width / meta.height;
    } catch (e) {
      row.w = 0;
      row.h = 0;
      row.aspect = 0;
    }
  }

  const allCols = (rows.columns || Object.keys(rows[0] || {})).filter(
    (c) => c && c !== 'id'
  );

  if (isPrecompute) {
    p.intro('Precompute gallery counts');

    // ── pick columns ──────────────────────────────────────
    /** @type {string[]} */
    let chosen;
    if (args[1]) {
      chosen = args[1].split(',').filter((c) => allCols.includes(c));
    }
    if (!chosen || !chosen.length) {
      chosen = await p.multiselect({
        message: 'Which columns to include?',
        required: true,
        options: allCols.map((c) => ({ value: c, label: fmt(c) })),
      });
      if (p.isCancel(chosen)) {
        p.cancel();
        process.exit(0);
      }
    }

    // ── ask which columns are multi-value ─────────────────
    const multiCols = new Set();
    const skipMulti = args[1] !== undefined;
    for (const col of chosen) {
      const multi = skipMulti
        ? col === 'category' || col === 'tags'
        : await p.confirm({
            message: `Does "${fmt(col)}" contain comma-separated values (tags)?`,
            activeLabel: 'Yes',
            inactiveLabel: 'No',
          });
      if (p.isCancel(multi)) {
        p.cancel();
        process.exit(0);
      }
      if (multi) multiCols.add(col);
    }

    // ── pick output component ─────────────────────────────
    const components = findComponentDirs('src/lib/components/custom/projects');
    if (!components.length) {
      p.cancel('No components found in src/lib/components/custom/projects/');
      process.exit(1);
    }
    let compDir;
    if (args[2]) {
      const match = components.find((c) => c.endsWith(args[2]));
      compDir = match ? resolve(ROOT, match) : resolve(ROOT, components[0]);
    } else {
      compDir = await p.select({
        message: 'Save the data next to which component?',
        options: components.map((f) => ({
          value: resolve(ROOT, f),
          label: f.replace('src/lib/components/', ''),
        })),
      });
      if (p.isCancel(compDir)) {
        p.cancel();
        process.exit(0);
      }
    }

    const csvName = basename(csvPath, '.csv');
    const outFile = resolve(compDir, 'data', `${csvName}-counts.js`);

    if (!existsSync(dirname(outFile)))
      mkdirSync(dirname(outFile), { recursive: true });

    const { code, data } = precomputeAll(rows, chosen, multiCols);
    writeFileSync(outFile, code, 'utf-8');

    const total = rows.length;
    p.log.info(
      `Wrote ${chosen.length} columns → ${outFile.replace(ROOT, '').slice(1)}`
    );
    for (const [col, vals] of Object.entries(data)) {
      p.log.info(
        `  ${col.padEnd(18)} ${String(vals.length).padStart(2)} unique values  (${total} rows)`
      );
    }
    p.outro('Done');
    return;
  }

  // ── interactive counter ─────────────────────────────────
  p.intro('Gallery data counter');

  const picked = await p.multiselect({
    message: 'Columns to group by',
    required: true,
    options: allCols.map((c) => ({ value: c, label: `${c}  —  ${fmt(c)}` })),
  });
  if (p.isCancel(picked)) {
    p.cancel();
    process.exit(0);
  }

  const multiCols = new Set();
  for (const col of picked) {
    const multi = await p.confirm({
      message: `Split "${fmt(col)}" on commas? (for tags, categories, etc.)`,
      activeLabel: 'Yes',
      inactiveLabel: 'No',
    });
    if (p.isCancel(multi)) {
      p.cancel();
      process.exit(0);
    }
    if (multi) multiCols.add(col);
  }

  const total = rows.length;

  for (const col of picked) {
    const sorted = count(rows, col, multiCols.has(col));

    p.log.info(`\n── ${fmt(col)} ──`);
    p.log.info(`Unique values: ${sorted.length}  (${total} rows)`);

    const maxLen = Math.max(
      ...sorted.map((d) => d.name.length),
      fmt(col).length
    );
    p.log.info(` ${fmt(col).padEnd(maxLen)}  Count  Pct     Distribution`);
    p.log.info('─'.repeat(maxLen + 34));
    for (const d of sorted) {
      const pct = ((d.value / total) * 100).toFixed(1);
      const barLen = Math.round((d.value / sorted[0].value) * 20);
      const bar = '█'.repeat(barLen);
      p.log.info(
        ` ${d.name.padEnd(maxLen)}  ${String(d.value).padStart(3)} (${pct.padStart(4)}%)  ${bar}`
      );
    }
  }

  // ── pick output component ─────────────────────────────
  const components = findComponentDirs('src/lib/components/custom/projects');
  if (!components.length) {
    p.cancel('No components found in src/lib/components/custom/projects/');
    process.exit(1);
  }
  const compDir = await p.select({
    message: 'Save the data next to which component?',
    options: components.map((f) => ({
      value: resolve(ROOT, f),
      label: f.replace('src/lib/components/', ''),
    })),
  });
  if (p.isCancel(compDir)) {
    p.cancel();
    process.exit(0);
  }

  const csvName = basename(csvPath, '.csv');
  const outFile = resolve(compDir, 'data', `${csvName}-counts.js`);
  if (!existsSync(dirname(outFile)))
    mkdirSync(dirname(outFile), { recursive: true });
  const { code } = precomputeAll(rows, picked, multiCols);
  writeFileSync(outFile, code, 'utf-8');
  p.log.info(
    `\nWrote precomputed file → ${outFile.replace(ROOT, '').slice(1)}`
  );

  p.outro(`Counted by ${picked.length} column(s)`);
}

main().catch((err) => {
  p.cancel('Script failed');
  console.error(err);
  process.exit(1);
});
